(in-package #:quasar.core)

(defun write-json-string (value stream)
  (check-type value string)
  (write-char #\" stream)
  (loop for character across value
        for code = (char-code character)
        do (case character
             (#\" (write-string "\\\"" stream))
             (#\\ (write-string "\\\\" stream))
             (#\Backspace (write-string "\\b" stream))
             (#\Page (write-string "\\f" stream))
             (#\Newline (write-string "\\n" stream))
             (#\Return (write-string "\\r" stream))
             (#\Tab (write-string "\\t" stream))
             (otherwise
              (if (< code 32)
                  (format stream "\\u~4,'0X" code)
                  (write-char character stream)))))
  (write-char #\" stream))

(defun encode-json-string (value)
  (with-output-to-string (stream)
    (write-json-string value stream)))

(defun write-json-coordinate (value stream)
  (cond
    ((integerp value)
     (princ value stream))
    ((realp value)
     (format stream "~,6F" (coerce value 'double-float)))
    (t
     (error 'graph-error
            :message (format nil "Cannot encode coordinate ~S." value)))))

(defun write-node-json (node stream)
  (write-string "{\"group\":\"nodes\",\"data\":{\"id\":" stream)
  (write-json-string (graph-node-id node) stream)
  (write-string ",\"label\":" stream)
  (write-json-string (graph-node-label node) stream)
  (write-string ",\"type\":" stream)
  (write-json-string (graph-node-type node) stream)
  (write-string "},\"position\":{\"x\":" stream)
  (write-json-coordinate (graph-node-x node) stream)
  (write-string ",\"y\":" stream)
  (write-json-coordinate (graph-node-y node) stream)
  (write-string "}}" stream))

(defun write-edge-json (edge stream)
  (write-string "{\"group\":\"edges\",\"data\":{\"id\":" stream)
  (write-json-string (graph-edge-id edge) stream)
  (write-string ",\"source\":" stream)
  (write-json-string (graph-edge-source edge) stream)
  (write-string ",\"target\":" stream)
  (write-json-string (graph-edge-target edge) stream)
  (write-string ",\"label\":" stream)
  (write-json-string (graph-edge-label edge) stream)
  (write-string ",\"type\":" stream)
  (write-json-string (graph-edge-type edge) stream)
  (write-string "}}" stream))

(defun graph->cytoscape-json (graph)
  (check-type graph graph-document)
  (with-output-to-string (stream)
    (write-string "{\"graphId\":" stream)
    (write-json-string (graph-id graph) stream)
    (write-string ",\"title\":" stream)
    (write-json-string (graph-title graph) stream)
    (format stream ",\"revision\":~D,\"elements\":[" (graph-revision graph))
    (let ((firstp t))
      (dolist (node (graph-nodes graph))
        (unless firstp
          (write-char #\, stream))
        (setf firstp nil)
        (write-node-json node stream))
      (dolist (edge (graph-edges graph))
        (unless firstp
          (write-char #\, stream))
        (setf firstp nil)
        (write-edge-json edge stream)))
    (write-string "]}" stream)))
